CREATE DATABASE KHOSACH
GO

USE KHOSACH

CREATE TABLE ANPHAM (
MASACH				CHAR (4) PRIMARY KEY,
TENSACH				NVARCHAR (50) NOT NULL,
DVT					NVARCHAR (10),
SL					INT NOT NULL, 
MALOAI				CHAR(1) NOT NULL
)

CREATE TABLE PHANLOAI (
MALOAI				CHAR(1) PRIMARY KEY CHECK (MALOAI IN ('A', 'B', 'C')),
TENLOAI				NVARCHAR(50) UNIQUE NOT NULL,
)

CREATE TABLE TACGIA (
MATG				CHAR (5) PRIMARY KEY,
HOTEN				NVARCHAR (50) NOT NULL,
NGAYSINH			DATE,
GIOITINH			NVARCHAR (10) CHECK (GIOITINH IN (N'Nam', N'Nữ')),
QUOCTICH			NVARCHAR (30)
)

CREATE TABLE CTTG (
MASACH				CHAR (4),
MATG				CHAR (5),
PRIMARY KEY (MASACH, MATG),
)

CREATE TABLE THELOAI (
MATL				CHAR (5) PRIMARY KEY,
TENTL				NVARCHAR (30) UNIQUE NOT NULL,
MOTA				NVARCHAR(100)
)

CREATE TABLE CTTL (
MASACH				CHAR (4),
MATL				CHAR (5),
PRIMARY KEY (MASACH, MATL),
)

CREATE TABLE VITRI (
MAVITRI				NVARCHAR (10) PRIMARY KEY,
KHUVUC				CHAR (1),
KE					CHAR (3),
TANG				CHAR (3)
)

CREATE TABLE CTVT (
MASACH				CHAR (4),
MAVITRI				NVARCHAR (10)
PRIMARY KEY (MASACH, MAVITRI)
)

CREATE TABLE KIEMKE (
MAKK				CHAR (5) PRIMARY KEY ,
NGAYKIEM			DATE NOT NULL,
MANV				VARCHAR(5)
)

CREATE TABLE CTKK (
MAKK				CHAR (5),
MASACH				CHAR(4),
SLDAT				INT,
SLKHONGDAT			INT,
CACHXULY			NVARCHAR(50) CHECK (CACHXULY IN (N'Hủy bỏ', N'Trả về nhà cung cấp')),
PRIMARY KEY (MAKK, MASACH)
)

CREATE TABLE NCC (
MANCC				VARCHAR (6) PRIMARY KEY,
TENNCC				NVARCHAR (50) NOT NULL,
DIACHI				NVARCHAR (50) NOT NULL,
SDT					VARCHAR (30) NOT NULL,
EMAIL				NVARCHAR (50)
)

CREATE TABLE PHIEUNHAP (
MAPN				VARCHAR (5) PRIMARY KEY,
NGAYNHAP			DATE NOT NULL,
MANCC				VARCHAR (6) NOT NULL,
MANV				VARCHAR(5) NOT NULL
)

CREATE TABLE CTPN (
MAPN				VARCHAR (5),
MASACH				CHAR (4),
SL					INT NOT NULL, 
DONGIA				MONEY NOT NULL CHECK (DONGIA > 0),
PRIMARY KEY (MAPN, MASACH),
)

CREATE TABLE DONHANG (
MADH				VARCHAR (5) PRIMARY KEY, 
NGAYXUAT			DATE NOT NULL,
MAKH				VARCHAR (10) NOT NULL,
MANV				VARCHAR (5) NOT NULL
)

CREATE TABLE CTDH (
MADH				VARCHAR (5),
MASACH				CHAR (4),
SL					INT NOT NULL,
DONGIA				MONEY NOT NULL CHECK (DONGIA > 0),
PRIMARY KEY (MADH, MASACH),
)

CREATE TABLE KHACHHANG (
MAKH				VARCHAR (10) PRIMARY KEY, 
TEN					NVARCHAR (50) NOT NULL,
DIACHI				NVARCHAR (50) NOT NULL,
SDT					VARCHAR (30) NOT NULL,
EMAIL				VARCHAR (50)
)

CREATE TABLE NHANVIEN (
MANV				VARCHAR (5) PRIMARY KEY,
HOTEN				NVARCHAR (50) NOT NULL,
GIOITINH			NVARCHAR (10) CHECK (GIOITINH IN (N'Nam', N'Nữ')),
CHUCVU				NVARCHAR (50) CHECK (CHUCVU IN (N'Nhân viên kho', N'Kế toán kho', N'Giám sát kho', N'Thủ kho')),
DIACHI				NVARCHAR (50),
SDT					VARCHAR (30) UNIQUE NOT NULL,
EMAIL				VARCHAR (50),
GIOLAM				INT 
)

CREATE TABLE HOADON (
MAHD				VARCHAR (10) PRIMARY KEY,
NGAYLAP				DATE NOT NULL,
MAKH				VARCHAR (10) NOT NULL,
MANV				VARCHAR (5) NOT NULL
)

CREATE TABLE CTHD (
MAHD				VARCHAR (10),
MASACH				CHAR (4),
SL					INT NOT NULL,
DONGIA				MONEY NOT NULL CHECK (DONGIA > 0),
PRIMARY KEY (MAHD, MASACH),
)



-- TẠO KHÓA NGOẠI 

ALTER TABLE ANPHAM
ADD CONSTRAINT FK_S_PL FOREIGN KEY (MALOAI) REFERENCES PHANLOAI(MALOAI)

ALTER TABLE CTTG
ADD CONSTRAINT FK_CTTG_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)
ALTER TABLE CTTG
ADD CONSTRAINT FK_CTTG_TG FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)

ALTER TABLE CTTL
ADD CONSTRAINT FK_CTTL_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)
ALTER TABLE CTTL 
ADD CONSTRAINT FK_CTTL_TL FOREIGN KEY (MATL) REFERENCES THELOAI(MATL)

ALTER TABLE CTVT
ADD CONSTRAINT FK_CTVT_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)
ALTER TABLE CTVT
ADD CONSTRAINT FK_CTVT_VT FOREIGN KEY (MAVITRI) REFERENCES VITRI(MAVITRI)

ALTER TABLE KIEMKE
ADD CONSTRAINT FK_KK_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTKK
ADD CONSTRAINT FK_CTKK_KK FOREIGN KEY (MAKK) REFERENCES KIEMKE(MAKK)

ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NCC(MANCC)
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DH_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DH_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN)
ALTER TABLE CTPN
ADD CONSTRAINT FK_CTPN_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)

ALTER TABLE CTDH
ADD CONSTRAINT FK_CTDH_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH)
ALTER TABLE CTDH
ADD CONSTRAINT FK_CTDH_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_S FOREIGN KEY (MASACH) REFERENCES ANPHAM(MASACH)





