-- SACH

INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S001', N'Truyện Kiều', '20x15 cm', N'Quyển', '47');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S002', N'Ngày xưa có một chuyện tình', '17x24 cm', N'Quyển', '35');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S003', N'Tôi thấy hoa vàng trên cỏ xanh', '13x19cm', N'Quyển', '37');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S004', N'Một đời như kẻ tìm đường', '16x24 cm', N'Quyển', '44');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S005', N'Harry Potter', '21x24cm', N'Bộ', '20');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S006', N'Nhóc Miko! Cô bé nhí nhảnh', '20x15 cm', N'Quyển', '51');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S007', N'Đừng bao giờ đi ăn một mình', '17x24 cm', N'Quyển', '71');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S008', N'Vừa nhắm mắt vừa mở cửa sổ', '13x19cm', N'Quyển', '6');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S009', N'Attack on Titan', '16x24 cm', N'Quyển', '13');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S010', N'Tiền không mua được gì', '21x24cm', N'Quyển', '41');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S011', N'Tiếp thị 5.0: Công nghệ vị nhân sinh', '20x15 cm', N'Bộ', '9');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S012', N'Bộ Manga - Nhóc Miko', '17x24 cm', 'Boxset', '11');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S013', N'Võ Nguyên Giáp - Hào khí trăm năm', '13x19cm', N'Quyển', '85');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S014', N'Dấn thân', '16x24 cm', N'Quyển', '72');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S015', N'1% Nỗ lực', '21x24cm', N'Quyển', '47');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S016', N'Thần thoại Sisyphus', '20x15 cm', N'Quyển', '63');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S017', N'Bí ẩn mãi mãi là bí ấn', '17x24 cm', N'Quyển', '45');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S018', N'Phật học tinh hoa', '13x19cm', N'Quyển', '90');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S019', N'Thuật tư tưởng', '16x24 cm', 'Boxset', '30');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S020', N'Biến thể của cô đơn', '21x24cm', 'Bộ', '75');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S021', N'Phòng trọ 3 người', '20x15 cm', N'Quyển', '92');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S022', N'War and Peace', '19x18 cm', N'Quyển', '116');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S023', 'Ulysses', '42x19 cm', N'Quyển', '24');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S024', 'Utopia', '22x48 cm', 'Boxset', '69');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S025', 'Waste Land', '18x22 cm', N'Quyển', '30');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S026', 'Treasure Island', '29x27 cm', N'Quyển', '35');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S027', 'Time Machine', '14x45 cm', N'Quyển', '49');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S028', 'The Tempest', '44x20 cm', N'Bộ', '29');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S029', 'Romeo and Juliet', '15x25 cm', N'Bộ', '109');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S030', 'Macbeth', '14x39 cm', N'Quyển', '6');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S031', 'The Merchant of Venice', '25x32 cm', N'Quyển', '54');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S032', 'Mein Kamph', '15x40 cm', N'Quyển', '97');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S033', 'The Great Gatsby', '26x12 cm', N'Quyển', '51');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S034', 'Wealth of Nations', '27x49 cm', N'Bộ', '48');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S035', 'The world as I see it', '29x47 cm', N'Quyển', '6');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S036', 'August 1914', '16x34 cm', N'Quyển', '72');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S037', 'Cherry Orchard', '31x16 cm', N'Quyển', '70');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S038', 'Politics', '37x34 cm', 'Boxset', '100');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S039', 'Divine Comedy', '39x11 cm', N'Quyển', '75');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S040', 'Illiad', '47x18 cm', N'Quyển', '109');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S041', 'Odyssey', '25x28 cm', N'Quyển', '94');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S042', 'Shape of things to come', '36x27 cm', 'Boxset', '90');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S043', 'Tropic of Cancer', '45x31 cm', N'Quyển', '65');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S044', 'Principia', '50x31 cm', N'Bộ', '37');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S045', 'Mother India', '10x32 cm', N'Quyển', '57');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S046', 'Paradise Lost', '23x16 cm', N'Quyển', '113');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S047', 'Lycidas', '50x25 cm', N'Quyển', '61');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S048', 'Republic', '41x11 cm', 'Boxset', '113');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S049', 'Descent of man', '12x43 cm', N'Quyển', '70');
INSERT INTO SACH (MASACH, TENSACH, KICHTHUOC, DVT, SL) VALUES ('S050', 'Origin of Species', '10x21 cm', N'Quyển', '64');


-- TACGIA

INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG01', N'Nguyễn Nhật Ánh', '09-04-1959', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG02', N'Thu Giang', '01-01-1970', N'Nữ', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG03', N'J.K. Rowling', '07-31-1965', N'Nữ', N'Anh');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG04', N'Nguyễn Duy Cẩn', '07-15-1907', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG05', N'Nguyễn Ngọc Tư', '01-20-1988', N'Nữ', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG06', N'Hồ Anh Thái', '11-27-1943', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG07', N'Nguyễn Ngọc Thuần', '04-22-1954', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG08', N'Sơn Nam', '12-11-1926', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG09', N'Phạm Toàn', '07-01-1932', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG10', N'Nguyễn Du', '01-03-1766', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG11', N'Eriko Ono', '05-05-1962', N'Nữ', N'Nhật Bản');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG12', N'Isayama Hajime', '08-29-1986', N'Nam', N'Nhật Bản');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG13', N'Yang Phan', '05-04-1958', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG14', N'Albert Camus', '11-07-1913', N'Nam', N'Pháp');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG15', N'Nishimura Hiroyuki', '11-16-1976', N'Nam', N'Nhật Bản');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG16', N'Sheryl Sandberg', '08-28-1969', N'Nữ', N'Hoa Kỳ');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG17', N'Trần Thái Bình', '10-10-1911', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG18', N'Philip Kotler', '05-27-1931', N'Nam', N'Hoa Kỳ');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG19', N'Michael Sandel', '03-05-1953', N'Nam', N'Hoa Kỳ');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG20', N'Keith Ferrazzi', '07-14-1966', N'Nam', N'Hoa Kỳ');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG21', N'Phan Văn Trường', '07-27-1946', N'Nam', N'Việt Nam');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG22', N'Mr. Susie Koelpin', '04-09-1911', N'Nữ', N'Hà Lan');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG23', N'Miss Erma Howell', '03-12-1910', N'Nữ', N'Ba Lan');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG24', N'Roland Walsh', '05-10-1996', N'Nam', N'Tây Ban Nha');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG25', N'Janie Swift', '06-24-1967', N'Nam', N'Đan Mạch');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG26', N'Tricia Pouros', '03-12-1928', N'Nam', N'Bỉ');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG27', N'Santos Bauch', '07-30-1972', N'Nam', N'Ý');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG28', N'Devin Bayer', '12-08-2001', N'Nam', N'Phần Lan');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG29', N'Minnie Gibson', '11-07-1975', N'Nữ', N'Nga');
INSERT INTO TACGIA (MATG, HOTEN, NGAYSINH, GIOITINH, QUOCTICH) VALUES ('TG30', N'Kristina DAmore', '12-01-1939', N'Nam', N'Na Uy');

-- CTTG

INSERT INTO CTTG (MASACH, MATG) VALUES ('S001', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S002', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S003', 'TG01');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S004', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S005', 'TG03');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S005', 'TG02');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S007', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S008', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S009', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S009', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S011', 'TG06');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S012', 'TG01');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S013', 'TG07');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S013', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S015', 'TG03');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S016', 'TG02');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S017', 'TG08');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S018', 'TG02');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S018', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S019', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S020', 'TG01');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S021', 'TG06');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S022', 'TG04');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S023', 'TG03');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S024', 'TG08');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S024', 'TG07');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S024', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S025', 'TG01');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S026', 'TG08');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S027', 'TG11');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S028', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S029', 'TG12');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S030', 'TG17');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S030', 'TG19');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S031', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S032', 'TG18');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S033', 'TG19');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S034', 'TG16');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S035', 'TG20');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S036', 'TG13');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S037', 'TG01');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S038', 'TG14');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S039', 'TG30');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S040', 'TG21');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S040', 'TG10');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S041', 'TG15');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S042', 'TG21');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S043', 'TG16');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S044', 'TG23');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S044', 'TG24');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S044', 'TG25');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S045', 'TG05');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S046', 'TG28');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S047', 'TG26');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S048', 'TG27');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S049', 'TG27');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S050', 'TG29');
INSERT INTO CTTG (MASACH, MATG) VALUES ('S050', 'TG09');

-- THELOAI

INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL001', N'Tâm lý, tình cảm', N'Truyện ngắn hay những cuốn tiểu thuyết dài kỳ.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL002', N'Tôn giáo', N'Sách nói về tư tưởng tôn giáo, nguồn gốc ra đời.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL003', N'Văn hoá xã hội', N'Sách nói về nhiều khía cạnh trong cuộc sống.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL004', N'Lịch sử', N'Sách nói về những dấu mốc những sự kiện lịch sử.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL005', N'Văn học viễn tưởng', N'Sách viết nên từ trí tưởng tượng của con người.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL006', N'Tiểu sử, tự truyện', N'Sách kể về cuộc đời hay những trải nghiệm có thật của chính tác giả. ');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL007', N'Kinh dị, bí ẩn', N'Sách phù thuỷ, pháp sư, ma quỷ, ám hại...');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL008', N'Dạy nấu ăn', N'Sách chứa  những bí quyết để tạo nên một món ăn.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL009', N'Khoa học công nghệ', N'Sách cung cấp các thông tin và các kiến thức liên quan tới khoa học và công nghệ.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL010', N'Truyền cảm hứng', N'Sách nội dung tích cực.');
INSERT INTO THELOAI (MATL, TENTL, MOTA) VALUES ('TL011', N'Thiếu nhi', N'Sách có nội dung gần gũi với cuộc sống.');

-- CTTL

j
INSERT INTO CTTL (MASACH, MATL) VALUES ('S001', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S001', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S002', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S003', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S004', 'TL005');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S005', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S006', 'TL009');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S006', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S007', 'TL005');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S008', 'TL011');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S009', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S010', 'TL006');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S011', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S011', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S012', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S013', 'TL007');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S014', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S015', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S016', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S016', 'TL011');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S017', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S018', 'TL006');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S019', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S020', 'TL005');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S020', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S020', 'TL009');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S021', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S022', 'TL009');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S022', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S023', 'TL006');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S024', 'TL010');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S025', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S026', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S027', 'TL009');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S028', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S029', 'TL011');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S030', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S030', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S031', 'TL011');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S032', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S033', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S034', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S035', 'TL005');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S035', 'TL004');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S036', 'TL008');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S037', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S038', 'TL007');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S039', 'TL009');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S039', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S039', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S040', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S041', 'TL010');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S042', 'TL003');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S043', 'TL008');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S044', 'TL007');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S044', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S045', 'TL010');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S046', 'TL008');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S047', 'TL002');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S047', 'TL007');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S048', 'TL001');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S049', 'TL008');
INSERT INTO CTTL (MASACH, MATL) VALUES ('S050', 'TL010');

-- VITRI

INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K01-T1', 'A', 'K01', 'T1');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K01-T2', 'A', 'K01', 'T2');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K01-T3', 'A', 'K01', 'T3');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K01-T4', 'A', 'K01', 'T4');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K01-T5', 'A', 'K01', 'T5');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K02-T1', 'A', 'K02', 'T1');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K02-T2', 'A', 'K02', 'T2');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K02-T3', 'A', 'K02', 'T3');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K02-T4', 'A', 'K02', 'T4');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K02-T5', 'A', 'K02', 'T5');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K03-T1', 'A', 'K03', 'T1');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K03-T2', 'A', 'K03', 'T2');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K03-T3', 'A', 'K03', 'T3');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K03-T4', 'A', 'K03', 'T4');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('A-K03-T5', 'A', 'K03', 'T5');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('B-K01-T1', 'B', 'K01', 'T1');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('B-K01-T2', 'B', 'K01', 'T2');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('B-K01-T3', 'B', 'K01', 'T3');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('B-K01-T4', 'B', 'K01', 'T4');
INSERT INTO VITRI (MAVITRI, KHUVUC, KE, TANG) VALUES ('B-K01-T5', 'B', 'K01', 'T5');

-- CTVT

INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S001', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S002', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S003', 'A-K03-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S004', 'A-K01-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S005', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S006', 'A-K02-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S006', 'A-K02-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S007', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S008', 'A-K01-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S009', 'A-K02-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S009', 'B-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S010', 'B-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S011', 'A-K03-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S012', 'A-K02-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S013', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S014', 'A-K03-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S014', 'A-K03-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S015', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S016', 'B-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S017', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S017', 'A-K03-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S018', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S019', 'B-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S020', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S021', 'A-K03-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S021', 'A-K02-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S022', 'A-K02-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S022', 'A-K02-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S023', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S024', 'A-K03-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S025', 'B-K01-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S026', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S027', 'A-K03-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S028', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S029', 'A-K01-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S029', 'A-K01-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S030', 'A-K03-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S031', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S032', 'A-K02-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S033', 'A-K01-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S033', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S034', 'A-K01-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S035', 'B-K01-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S036', 'A-K02-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S037', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S038', 'A-K03-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S038', 'A-K02-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S038', 'B-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S039', 'A-K03-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S040', 'A-K01-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S041', 'B-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S042', 'A-K02-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S042', 'A-K02-T3');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S043', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S044', 'A-K03-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S044', 'A-K01-T2');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S045', 'A-K02-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S046', 'A-K03-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S047', 'A-K02-T5');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S048', 'A-K01-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S048', 'A-K01-T1');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S049', 'A-K01-T4');
INSERT INTO CTVT (MASACH, MAVITRI) VALUES ('S050', 'A-K02-T3');

-- NCC

INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC01', N'Nhà In Sài Gòn', N'123 Nguyễn Thị Minh Khai, Quận 1, Hồ Chí Minh', '02838223333', 'nhainsg@gmail.com');
INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC02', N'Nhà In Tiến Bộ', N'45 Trường Chinh, Quận Tân Bình, Hồ Chí Minh', '02838654444', 'tienbo.print@gmail.com');
INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC03', N'Nhà In Hòa Bình', N'78 Lê Quang Đạo, Quận 4, Hồ Chí Minh', '02839125555', 'hoabinhnprint@gmail.com');
INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC04', N'Nhà In Minh Long', N'12 Phan Đình Phùng, Quận Phú Nhuận, Hồ Chí Minh', '02839936666', 'minhlong.print@gmail.com');
INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC05', N'Nhà In Đại Việt', N'89 Lý Thái Tổ, Quận 10, Hồ Chí Minh', '02838517777', 'daivietprinting@gmail.com');
INSERT INTO NCC (MANCC, TENNCC, DIACHI, SDT, EMAIL) VALUES ('NCC06', N'Nhà In Thành Công', N'56 Võ Thị Sáu, Quận 3, Hồ Chí Minh', '02838278888', 'thanhcongpress@gmail.com');

-- NHANVIEN

INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV01', N'Trịnh Trần Phương Tuấn', N'Nam ', N'Thủ kho', '0526170972', 'tuantrinh@gmail.com', '222');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV02', N'Đỗ Phú Quí', N'Nam ', N'Giám sát kho', '0526170973', 'quido@gmail.com', '186');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV03', N'Trần Minh Hiếu', N'Nam ', N'Kế toán kho', '0526170974', 'hieutran@gmail.com', '208');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV04', N'Nguyễn Thanh Tùng', N'Nam ', N'Nhân viên kho', '0526170975', 'tungnguyen@gmail.com', '242');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV05', N'Nguyễn Bảo Khánh', N'Nam ', N'Nhân viên kho', '0526170976', 'khanhnguyen@gmail.com', '201');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV06', N'Lê Trung Kiên', N'Nam ', N'Nhân viên kho', '0526170977', 'kienle@gmail.com', '230');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV07', N'Hoàng Việt Bảo Minh', N'Nam ', N'Nhân viên kho', '0526170978', 'minhhoang@gmail.com', '185');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV08', N'Nghiêm Vũ Hoàng Long', N'Nam ', N'Nhân viên kho', '0526170979', 'longnghiem@gmail.com', '161');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV09', N'Nguyễn Thảo Linh', N'Nữ', N'Nhân viên kho', '0526170980', 'linhnguyen@gmail.com', '169');
INSERT INTO NHANVIEN (MANV, HOTEN, GIOITINH, CHUCVU, SDT, EMAIL, GIOLAM) VALUES ('NV10', N'Phương Mỹ Chi', N'Nữ', N'Nhân viên kho', '0526170981', 'chiphuong@gmail.com', '231');


-- PHIEUNHAP

INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN001', '2024-01-01', 'NCC01', 'NV04');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN002', '2024-01-15', 'NCC02', 'NV05');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN003', '2024-02-01', 'NCC06', 'NV06');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN004', '2024-02-15', 'NCC04', 'NV07');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN005', '2024-03-01', 'NCC05', 'NV07');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN006', '2024-03-15', 'NCC06', 'NV04');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN007', '2024-04-01', 'NCC03', 'NV10');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN008', '2024-04-15', 'NCC02', 'NV10');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN009', '2024-05-01', 'NCC06', 'NV10');
INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN010', '2024-05-15', 'NCC01', 'NV04');

-- CTPN

INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN001', 'S001', '12', '100000 ');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN002', 'S002', '12', '125000 ');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN003', 'S003', '24', '100000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN004', 'S004', '39', '150000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S005', '33', '2950000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S006', '31', '100000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN007', 'S007', '27', '250000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN008', 'S008', '38', '190000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN009', 'S009', '39', '300000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S010', '38', '470000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S011', '13', '520000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S012', '50', '780000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN007', 'S013', '49', '190000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN008', 'S014', '49', '200000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN009', 'S015', '45', '270000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN001', 'S016', '5', '230000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S017', '6', '210000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S018', '18', '100000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S019', '29', '1500000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S020', '11', '1900000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S021', '3', '200000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN001', 'S022', '4', '340000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S023', '23', '280000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S024', '16', '2700000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S025', '5', '300000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN001', 'S026', '46', '299000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN002', 'S027', '7', '220000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN003', 'S028', '7', '610000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN004', 'S029', '43', '540000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S030', '30', '190000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S031', '11', '180000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S032', '37', '190000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S033', '24', '300000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S034', '9', '1500000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S035', '20', '300000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN001', 'S036', '17', '200000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN002', 'S037', '21', '199000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN003', 'S038', '35', '1800000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN004', 'S039', '25', '240000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S040', '42', '310000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S041', '43', '220000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S042', '37', '2100000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S043', '37', '320000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S044', '23', '870000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S045', '9', '280000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S046', '3', '450000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S047', '40', '300000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN010', 'S048', '10', '1200000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN005', 'S049', '9', '185000');
INSERT INTO CTPN (MAPN, MASACH, SL, DONGIA) VALUES ('PN006', 'S050', '23', '399000');

-- KHACHHANG

INSERT INTO KHACHHANG(MAKH, HOTEN, DIACHI, SDT, EMAIL)
VALUES
('KH01', N'Cá Chép', '211 Võ Văn Tần, Phường 5, Quận 3, Hồ Chí Minh', '028 6290 6951', 'cachep@gmail.com'),
('KH02', N'Nhã Nam', '120 Trần Phú, Phường 4, Quận 5, Hồ Chí Minh', '028 3928 9876', 'nhanam@gmail.com'),
('KH03', N'FAHASA', '456 Nguyễn Thị Minh Khai, Quận 1, Hồ Chí Minh', '028 3833 1122', 'fahasa@gmail.com'),
('KH04', N'ArtBook', '25 Nguyễn Huệ, Quận 1, Hồ Chí Minh', '028 3823 2333', 'artbook@gmail.com'),
('KH05', N'Alpha Books', '34 Lê Lợi, Quận 1, Hồ Chí Minh', '028 3920 4444', 'alphabooks@gmail.com'),
('KH06', N'Hải An', '88 Cao Thắng, Phường 12, Quận 10, Hồ Chí Minh', '028 3962 5555', 'haian@gmail.com'),
('KH07', N'Phương Nam', '106 Lê Duẩn, Quận 1, Hồ Chí Minh', '028 3831 6666', 'phuongnam@gmail.com'),
('KH08', N'Tổng hợp', '15 Trường Chinh, Quận Tân Bình, Hồ Chí Minh', '028 3867 7777', 'tonghop@gmail.com'),
('KH09', N'E.Book', '7 Nguyễn Cảnh Dị, Quận Bình Thạnh, Hồ Chí Minh', '028 3898 8888', 'e.book@gmail.com'),
('KH10', N'Kim Đồng', '72 Nguyễn Thái Học, Quận 10, Hồ Chí Minh', '028 3832 9999', 'kimdong@gmail.com'),
('KH11', N'Tràng An', '50 Lý Tự Trọng, Quận 1, Hồ Chí Minh', '028 3928 1111', 'trangan@gmail.com'),
('KH12', N'Trí Đức', '123 Phan Đình Phùng, Quận Phú Nhuận, Hồ Chí Minh', '028 3899 0000', 'triduc@gmail.com');

-- PHIEUXUAT

INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX001', '2024-09-05', 'KH01', 'NV04');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX002', '2024-09-11', 'KH02', 'NV05');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX003', '2024-09-15', 'KH03', 'NV06');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX004', '2024-09-25', 'KH04', 'NV07');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX005', '2024-10-10', 'KH05', 'NV08');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX006', '2024-10-18', 'KH06', 'NV09');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX007', '2024-10-29', 'KH07', 'NV10');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX008', '2024-11-02', 'KH08', 'NV06');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX009', '2024-11-13', 'KH09', 'NV08');
INSERT INTO PHIEUXUAT (MAPX, NGAYXUAT, MAKH, MANV) VALUES ('PX010', '2024-11-25', 'KH10', 'NV05');

-- CTPX

INSERT INTO CTPX (MAPX, MASACH, SL, DONGIA)
VALUES
('PX001', 'S006', 7, 100000),
('PX002', 'S003', 6, 100000),
('PX003', 'S014', 12, 200000),
('PX004', 'S015', 20, 270000),
('PX005', 'S020', 2, 1900000),
('PX006', 'S033', 3, 300000),
('PX007', 'S043', 30, 320000),
('PX008', 'S050', 4, 399000),
('PX009', 'S047', 1, 300000),
('PX010', 'S001', 2, 100000);



