﻿-- Liệt kê tác giả có lượng sách ra nhiều nhất trong năm 2024 
SELECT TOP 1 TG.HOTEN, MAX(CTHD.SL) AS SoLuongBan
FROM TACGIA TG JOIN CTTG ON TG.MATG = CTTG.MATG
JOIN CTHD ON CTTG.MASACH = CTHD.MASACH
JOIN HOADON HD ON CTHD.MAHD = HD.MAHD
WHERE HD.NGAYLAP BETWEEN '2024-01-01' AND '2024-12-31' 
GROUP BY TG.HOTEN
ORDER BY SoLuongBan DESC;

-- Lấy thông tin của sách theo tác giả Nguyễn Nhật Ánh
SELECT * 
FROM ANPHAM S JOIN CTTG ON S.MASACH = CTTG.MASACH
WHERE MATG = 'TG01';

-- Lấy tất cả các sách có số lượng trên 100 quyển
SELECT *
FROM ANPHAM
WHERE SL > 100

-- Truy vấn sách thể loại Lịch sử
SELECT *
FROM ANPHAM S JOIN CTTL ON S.MASACH = CTTL.MASACH
WHERE MATL = 'TL004'
 
 --Liệt kê những quyển sách nằm ở kệ 1 và tầng 3
 SELECT *
 FROM (ANPHAM S JOIN CTVT ON S.MASACH = CTVT.MASACH)
  JOIN VITRI VT ON CTVT.MAVITRI = VT.MAVITRI
 WHERE VT.KE = 'K01' AND VT.TANG = 'T03'

-- Liệt kê  danh sách các sách được mua nhiều nhất từ cao tới thấp
SELECT S.MASACH, S.TENSACH, SUM(CTDH.SL) AS TongSoLuong
FROM ANPHAM S JOIN CTDH CTDH ON S.MASACH = CTDH.MASACH
GROUP BY S.MASACH, S.TENSACH
ORDER BY TongSoLuong DESC;

-- Chỉ ra sách có số lượng lớn nhất trong đơn hàng
SELECT TOP 1 S.MASACH, S.TENSACH, MAX(CTDH.SL) AS SoLuongMax
FROM ANPHAM S
JOIN CTDH CTDH ON S.MASACH = CTDH.MASACH
GROUP BY S.MASACH, S.TENSACH
ORDER BY SoLuongMax DESC;

-- Thống kê số lượng sách theo thể loại
SELECT CTTL.MATL, TL.TENTL, S.TENSACH, COUNT(S.MASACH) AS SoLuongSach
FROM (CTTL JOIN ANPHAM S ON CTTL.MASACH = S.MASACH) JOIN THELOAI TL ON CTTL.MATL = TL.MATL
GROUP BY CTTL.MATL, TL.TENTL, S.TENSACH;

-- Lập danh sách các quyển sách được bán trong năm 2024
SELECT HD.MAHD, CTHD.MASACH, S.TENSACH, SUM(CTHD.SL) AS SoLuongBan
FROM HOADON HD JOIN CTHD ON HD.MAHD = CTHD.MAHD
JOIN ANPHAM S ON CTHD.MASACH = S.MASACH
WHERE HD.NGAYLAP BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY HD.MAHD, CTHD.MASACH, S.TENSACH
ORDER BY SoLuongBan DESC;	

-- Lập danh sách các quyển sách được nhập trong năm 2024
SELECT PN.NGAYNHAP, CTPN.MASACH, S.TENSACH, CTPN.SL AS SoLuongNhap
FROM PHIEUNHAP PN JOIN CTPN ON PN.MAPN = CTPN.MAPN 
JOIN ANPHAM S ON S.MASACH = CTPN.MASACH
WHERE PN.NGAYNHAP BETWEEN '2024-01-01' AND '2024-12-31'
ORDER BY PN.NGAYNHAP DESC;

-- Liệt kê số lượng sách tồn kho theo số lượng cụ thể
SELECT TL.TENTL, S.TENSACH, S.SL AS SoLuongTon
FROM ANPHAM S JOIN CTTL ON S.MASACH = CTTL.MASACH
JOIN THELOAI TL ON CTTL.MATL = TL.MATL
ORDER BY TL.TENTL, S.TENSACH

-- Liệt kê khách hàng mua nhiều nhất trong 6 tháng đầu năm 2024
SELECT TOP 1 KH.TEN, KH.DIACHI, KH.EMAIL, KH.SDT, MAX(CTHD.SL) AS SoLuongMua
FROM KHACHHANG KH JOIN HOADON HD ON KH.MAKH = HD.MAKH
JOIN CTHD ON HD.MAHD = CTHD.MAHD
WHERE HD.NGAYLAP BETWEEN '2024-01-01' AND '2024-06-01'
GROUP BY KH.TEN, KH.DIACHI, KH.EMAIL, KH.SDT, CTHD.SL
ORDER BY CTHD.SL DESC

-- Thể loại nào được khách hàng mua ít nhất trong năm 2024
SELECT TOP 1 TL.TENTL, TL.MOTA, MIN(CTHD.SL) AS SoLuongBan
FROM CTHD JOIN CTTL ON CTHD.MASACH = CTTL.MASACH
JOIN THELOAI TL ON CTTL.MATL = TL.MATL
GROUP BY TL.TENTL, TL.MOTA
ORDER BY SoLuongBan

-- Sách của tác giả nào được mua ít nhất trong năm 2024
SELECT TOP 1 S.TENSACH, TG.HOTEN, MIN(CTHD.SL) AS SoLuongMua
FROM ANPHAM S JOIN CTHD ON S.MASACH = CTHD.MASACH
JOIN CTTG ON CTTG.MASACH = S.MASACH
JOIN TACGIA TG ON TG.MATG = CTTG.MATG
GROUP BY S.TENSACH, TG.HOTEN
ORDER BY SoLuongMua

-- KH nào không đặt đơn trong năm qua
SELECT *
FROM KHACHHANG KH LEFT JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE HD.MAHD IS NULL  

